import { images as img } from "./images.js";

// Prices are in SAR, close to Saudi retail. Within each category the list runs
// from most to least prominent; the seed staggers createdAt in that order.
export const products = [
	// Smartphones
	{
		name: "iPhone 17 Pro Max 256GB",
		category: "Smartphones",
		price: 5099,
		stock: 18,
		featured: true,
		image: img.iphoneProDark,
		images: [img.iphoneProWhite],
		description: "شاشة Super Retina XDR مقاس 6.9 بوصة بتقنية ProMotion، شريحة A19 Pro، نظام كاميرات Pro بثلاث عدسات 48 ميجابكسل وبطارية تدوم طوال اليوم. ضمان الوكيل سنة.",
		tags: ["apple", "iphone", "5g"],
	},
	{
		name: "iPhone 17 Pro 256GB",
		category: "Smartphones",
		price: 4599,
		stock: 22,
		image: img.iphoneProWhite,
		images: [img.iphoneProDark],
		description: "شاشة 6.3 بوصة بتقنية ProMotion حتى 120 هرتز، شريحة A19 Pro، تصوير فيديو 4K بدقة 120 إطارًا وهيكل من الألومنيوم.",
		tags: ["apple", "iphone", "5g"],
	},
	{
		name: "iPhone Air 256GB",
		category: "Smartphones",
		price: 4299,
		stock: 9,
		image: img.iphoneWhite,
		description: "أنحف iPhone على الإطلاق بسماكة 5.6 ملم، شاشة 6.5 بوصة، شريحة A19 Pro وكاميرا Fusion بدقة 48 ميجابكسل.",
		tags: ["apple", "iphone"],
	},
	{
		name: "iPhone 17 256GB",
		category: "Smartphones",
		price: 3499,
		stock: 35,
		image: img.iphone15,
		description: "شاشة 6.3 بوصة بمعدل تحديث 120 هرتز، شريحة A19، كاميرا أمامية Center Stage وسعة تخزين 256 جيجابايت.",
		tags: ["apple", "iphone", "5g"],
	},
	{
		name: "Samsung Galaxy S25 Ultra 256GB",
		category: "Smartphones",
		price: 4199,
		stock: 16,
		featured: true,
		image: img.samsungGalaxy,
		description: "شاشة Dynamic AMOLED 2X مقاس 6.9 بوصة، معالج Snapdragon 8 Elite for Galaxy، كاميرا 200 ميجابكسل وقلم S Pen مدمج مع ميزات Galaxy AI.",
		tags: ["samsung", "android", "5g"],
	},
	{
		name: "Samsung Galaxy Z Fold7 256GB",
		category: "Smartphones",
		price: 7399,
		stock: 4,
		image: img.androidGold,
		description: "هاتف قابل للطي بشاشة داخلية 8 بوصة وخارجية 6.5 بوصة، كاميرا 200 ميجابكسل ووزن 215 جرامًا فقط.",
		tags: ["samsung", "foldable", "5g"],
	},
	{
		name: "Samsung Galaxy Z Flip7 256GB",
		category: "Smartphones",
		price: 4299,
		stock: 11,
		image: img.phoneInHand,
		description: "تصميم قابل للطي بحجم الجيب، شاشة خارجية FlexWindow مقاس 4.1 بوصة وبطارية 4300 مللي أمبير.",
		tags: ["samsung", "foldable"],
	},
	{
		name: "Samsung Galaxy A56 5G 256GB",
		category: "Smartphones",
		price: 1599,
		stock: 48,
		image: img.androidDark,
		description: "شاشة Super AMOLED مقاس 6.7 بوصة بمعدل 120 هرتز، كاميرا 50 ميجابكسل، شحن سريع 45 واط وتحديثات لست سنوات.",
		tags: ["samsung", "android", "5g"],
	},
	{
		name: "Huawei Pura 80 Pro 512GB",
		category: "Smartphones",
		price: 4699,
		stock: 7,
		image: img.androidGold,
		description: "كاميرا XMAGE بعدسة رئيسية بفتحة متغيرة وعدسة تقريب مزدوجة، شاشة 6.8 بوصة وشحن سلكي 100 واط.",
		tags: ["huawei", "android"],
	},
	{
		name: "Xiaomi 15 Ultra 512GB",
		category: "Smartphones",
		price: 4999,
		stock: 0,
		image: img.androidDark,
		description: "نظام كاميرات Leica رباعي مع مستشعر 1 بوصة، معالج Snapdragon 8 Elite وشاشة WQHD+ مقاس 6.73 بوصة.",
		tags: ["xiaomi", "android", "leica"],
	},
	{
		name: "Xiaomi Redmi Note 14 Pro+ 5G 512GB",
		category: "Smartphones",
		price: 1699,
		stock: 40,
		image: img.phoneFront,
		description: "كاميرا 200 ميجابكسل، شاشة AMOLED منحنية 6.67 بوصة، شحن HyperCharge بقدرة 120 واط ومقاومة للماء IP68.",
		tags: ["xiaomi", "redmi", "android"],
	},
	{
		name: "iPhone 16e 128GB",
		category: "Smartphones",
		price: 2499,
		stock: 27,
		image: img.iphoneRed,
		description: "شريحة A18، كاميرا Fusion بدقة 48 ميجابكسل، شاشة 6.1 بوصة ودعم Apple Intelligence بسعر مناسب.",
		tags: ["apple", "iphone"],
	},

	// Laptops
	{
		name: "MacBook Air 13 M4 16GB 256GB",
		category: "Laptops",
		price: 4199,
		stock: 24,
		featured: true,
		image: img.macbookAir,
		images: [img.macbookSilver],
		description: "شريحة Apple M4 بمعالج 10 أنوية، ذاكرة موحدة 16 جيجابايت، شاشة Liquid Retina مقاس 13.6 بوصة وبطارية حتى 18 ساعة. لوحة مفاتيح عربي/إنجليزي.",
		tags: ["apple", "macbook"],
	},
	{
		name: "MacBook Pro 14 M5 16GB 512GB",
		category: "Laptops",
		price: 6999,
		stock: 10,
		image: img.macbookPro,
		images: [img.macbookPurple],
		description: "شريحة M5 بأداء رسومي أعلى للذكاء الاصطناعي، شاشة Liquid Retina XDR مقاس 14.2 بوصة، منافذ Thunderbolt 4 وHDMI.",
		tags: ["apple", "macbook", "pro"],
	},
	{
		name: "MacBook Air 15 M4 16GB 512GB",
		category: "Laptops",
		price: 5999,
		stock: 8,
		image: img.macbookDesk,
		description: "شاشة 15.3 بوصة بتصميم نحيف، شريحة M4، أربع سماعات بصوت مكاني وسعة تخزين 512 جيجابايت.",
		tags: ["apple", "macbook"],
	},
	{
		name: "Lenovo Legion Pro 5i Gen 10 RTX 5070",
		category: "Laptops",
		price: 7499,
		stock: 6,
		featured: true,
		image: img.gamingLaptop,
		description: "معالج Intel Core Ultra 9 275HX، بطاقة GeForce RTX 5070، شاشة OLED مقاس 16 بوصة بمعدل 240 هرتز وذاكرة 32 جيجابايت DDR5.",
		tags: ["lenovo", "legion", "gaming"],
	},
	{
		name: "ASUS ROG Zephyrus G16 RTX 5080",
		category: "Laptops",
		price: 12999,
		stock: 3,
		image: img.gamingLaptop,
		description: "هيكل ألومنيوم نحيف، معالج Intel Core Ultra 9، بطاقة RTX 5080، شاشة ROG Nebula OLED بدقة 2.5K و240 هرتز.",
		tags: ["asus", "rog", "gaming"],
	},
	{
		name: "Dell XPS 13 9350 Core Ultra 7",
		category: "Laptops",
		price: 6999,
		stock: 8,
		image: img.laptopWhite,
		description: "معالج Intel Core Ultra 7 258V مع وحدة NPU للذكاء الاصطناعي، شاشة 13.4 بوصة وذاكرة 16 جيجابايت في هيكل خفيف.",
		tags: ["dell", "xps", "ultrabook"],
	},
	{
		name: "HP Victus 15 Core i5 RTX 4050",
		category: "Laptops",
		price: 3499,
		stock: 19,
		image: img.gamingLaptop,
		description: "لابتوب ألعاب بسعر مناسب: معالج Core i5-13420H، بطاقة RTX 4050، شاشة FHD بمعدل 144 هرتز و16 جيجابايت رام.",
		tags: ["hp", "victus", "gaming"],
	},
	{
		name: "Lenovo ThinkPad X1 Carbon Gen 13",
		category: "Laptops",
		price: 8999,
		stock: 4,
		image: img.dellLaptop,
		description: "لابتوب أعمال بوزن أقل من 1 كجم، معالج Core Ultra 7، شاشة 2.8K OLED وحماية بمستوى المؤسسات.",
		tags: ["lenovo", "thinkpad", "business"],
	},
	{
		name: "ASUS TUF Gaming A15 RTX 4060",
		category: "Laptops",
		price: 4299,
		stock: 14,
		image: img.gamingLaptop,
		description: "معالج AMD Ryzen 7 7735HS، بطاقة RTX 4060، شاشة 15.6 بوصة بمعدل 144 هرتز ومتانة بمعايير عسكرية.",
		tags: ["asus", "tuf", "gaming"],
	},
	{
		name: "Lenovo IdeaPad Slim 5 14 Ryzen 7",
		category: "Laptops",
		price: 2999,
		stock: 21,
		image: img.laptopWhite,
		description: "لابتوب خفيف للدراسة والعمل بمعالج Ryzen 7 8845HS، ذاكرة 16 جيجابايت وشاشة WUXGA OLED.",
		tags: ["lenovo", "ideapad"],
	},
	{
		name: "Dell Inspiron 15 3530 Core i5",
		category: "Laptops",
		price: 2299,
		stock: 30,
		image: img.dellLaptop,
		description: "لابتوب يومي بمعالج Core i5-1334U، ذاكرة 8 جيجابايت، SSD سعة 512 جيجابايت وشاشة 15.6 بوصة بمعدل 120 هرتز.",
		tags: ["dell", "inspiron"],
	},

	// Gaming
	{
		name: "PlayStation 5 Pro",
		category: "Gaming",
		price: 2999,
		stock: 12,
		featured: true,
		image: img.ps5,
		description: "أقوى جهاز PlayStation مع رسومات PSSR المحسّنة، تتبع الأشعة المتقدم وتخزين SSD سعة 2 تيرابايت. نسخة الشرق الأوسط.",
		tags: ["sony", "playstation", "console"],
	},
	{
		name: "PlayStation 5 Slim Digital Edition",
		category: "Gaming",
		price: 1899,
		stock: 25,
		image: img.ps5,
		description: "تصميم أنحف بسعة 1 تيرابايت، تحميل فائق السرعة ودعم ألعاب PS5 وPS4 الرقمية.",
		tags: ["sony", "playstation", "console"],
	},
	{
		name: "Nintendo Switch 2",
		category: "Gaming",
		price: 1849,
		stock: 2,
		image: img.controllerNeon,
		description: "شاشة LCD مقاس 7.9 بوصة بدقة 1080p، دعم 4K على التلفاز، أذرع Joy-Con 2 مغناطيسية وتخزين 256 جيجابايت.",
		tags: ["nintendo", "console"],
	},
	{
		name: "Xbox Series X 1TB",
		category: "Gaming",
		price: 2199,
		stock: 9,
		image: img.xboxSeriesX,
		description: "ألعاب بدقة 4K حتى 120 إطارًا، تقنية Quick Resume وتوافق مع آلاف الألعاب عبر Game Pass.",
		tags: ["microsoft", "xbox", "console"],
	},
	{
		name: "DualSense Wireless Controller",
		category: "Gaming",
		price: 299,
		stock: 60,
		image: img.controllerDark,
		description: "ذراع تحكم PS5 مع اهتزاز لمسي ومحفزات تكيفية وميكروفون مدمج.",
		tags: ["sony", "playstation", "controller"],
	},
	{
		name: "Xbox Wireless Controller Carbon Black",
		category: "Gaming",
		price: 249,
		stock: 45,
		image: img.xboxController,
		description: "ذراع تحكم لاسلكي متوافق مع Xbox وPC والهواتف، قبضة محكمة وزر مشاركة.",
		tags: ["microsoft", "xbox", "controller"],
	},
	{
		name: "Logitech G Pro X Superlight 2",
		category: "Gaming",
		price: 649,
		stock: 17,
		image: img.gamingMouse,
		description: "فأرة ألعاب لاسلكية بوزن 60 جرامًا، مستشعر HERO 2 بدقة 32,000 DPI وبطارية حتى 95 ساعة.",
		tags: ["logitech", "mouse", "esports"],
	},
	{
		name: "ASUS ROG Strix G16CH Desktop RTX 4070",
		category: "Gaming",
		price: 8499,
		stock: 3,
		image: img.gamingPc,
		description: "جهاز ألعاب مكتبي بمعالج Intel Core i7-14700F، بطاقة RTX 4070 Super، ذاكرة 32 جيجابايت وSSD سعة 1 تيرابايت مع إضاءة Aura RGB.",
		tags: ["asus", "rog", "desktop", "pc"],
	},

	// Smart Home
	{
		name: "Amazon Echo Dot 5th Gen",
		category: "Smart Home",
		price: 249,
		stock: 55,
		image: img.smartSpeaker,
		description: "مكبر صوت ذكي مع Alexa باللهجة الخليجية، تحكم بالأجهزة المنزلية وصوت أوضح من الجيل السابق.",
		tags: ["amazon", "alexa", "speaker"],
	},
	{
		name: "Apple TV 4K 128GB",
		category: "Smart Home",
		price: 749,
		stock: 13,
		image: img.smartTv,
		description: "جهاز بث بدقة 4K HDR مع Dolby Vision وDolby Atmos، شريحة A15 Bionic ويعمل كمركز للمنزل الذكي.",
		tags: ["apple", "streaming"],
	},
	{
		name: "Nuki Smart Lock Pro 4th Gen",
		category: "Smart Home",
		price: 1099,
		stock: 6,
		image: img.smartHomeDevices,
		description: "قفل ذكي يركب على القفل الحالي دون تغيير الباب، يدعم Matter وWi-Fi وفتح الباب تلقائيًا عند الاقتراب.",
		tags: ["nuki", "lock", "matter"],
	},
	{
		name: "Amazon Echo 4th Gen",
		category: "Smart Home",
		price: 449,
		stock: 20,
		image: img.smartSpeaker,
		description: "مكبر صوت ذكي بصوت غني ومحور Zigbee مدمج للتحكم بالإضاءة والمقابس الذكية.",
		tags: ["amazon", "alexa", "speaker"],
	},
	{
		name: "Apple HomePod mini",
		category: "Smart Home",
		price: 449,
		stock: 15,
		image: img.smartSpeaker,
		description: "مكبر صوت ذكي صغير بصوت 360 درجة، يعمل مع Siri ويتحكم بأجهزة Apple Home.",
		tags: ["apple", "siri", "speaker"],
	},

	// Audio
	{
		name: "AirPods Pro 3",
		category: "Audio",
		price: 999,
		stock: 42,
		featured: true,
		image: img.airpodsPro,
		description: "عزل ضوضاء نشط أقوى بمرتين، قياس نبض القلب أثناء التمرين، مقاومة للماء والعرق IP57 وعلبة شحن USB-C.",
		tags: ["apple", "airpods", "anc"],
	},
	{
		name: "Sony WH-1000XM6",
		category: "Audio",
		price: 1699,
		stock: 11,
		featured: true,
		image: img.sonyHeadphones,
		description: "سماعة رأس لاسلكية بأفضل عزل ضوضاء من Sony، معالج QN3، بطارية 30 ساعة وتصميم قابل للطي.",
		tags: ["sony", "headphones", "anc"],
	},
	{
		name: "AirPods 4 with Active Noise Cancellation",
		category: "Audio",
		price: 799,
		stock: 33,
		image: img.airpods,
		description: "تصميم مفتوح مريح مع عزل نشط للضوضاء، صوت مكاني مخصص وعلبة شحن لاسلكية.",
		tags: ["apple", "airpods"],
	},
	{
		name: "AirPods Max USB-C",
		category: "Audio",
		price: 2199,
		stock: 7,
		image: img.headphonesGrey,
		description: "سماعة رأس فاخرة بصوت Hi-Fi، عزل ضوضاء نشط، صوت مكاني ومنفذ USB-C.",
		tags: ["apple", "headphones"],
	},
	{
		name: "Samsung Galaxy Buds3 Pro",
		category: "Audio",
		price: 899,
		stock: 19,
		image: img.earbudsDark,
		description: "سماعات أذن بعزل ضوضاء ذكي، ترجمة فورية عبر Galaxy AI وصوت 24 بت Hi-Fi.",
		tags: ["samsung", "earbuds", "anc"],
	},
	{
		name: "JBL Flip 7",
		category: "Audio",
		price: 549,
		stock: 28,
		image: img.jblSpeaker,
		description: "مكبر صوت محمول مقاوم للماء والغبار IP68 ومقاوم للسقوط، صوت JBL Pro وبطارية 14 ساعة.",
		tags: ["jbl", "speaker", "bluetooth"],
	},
	{
		name: "JBL Charge 6",
		category: "Audio",
		price: 749,
		stock: 16,
		image: img.jblSpeaker,
		description: "مكبر صوت بقوة أعلى وبطارية حتى 24 ساعة، يعمل كباور بانك لشحن هاتفك، مقاوم للماء IP68.",
		tags: ["jbl", "speaker", "bluetooth"],
	},
	{
		name: "Anker Soundcore Liberty 4 Pro",
		category: "Audio",
		price: 499,
		stock: 24,
		image: img.earbudsCases,
		description: "سماعات أذن بعزل ضوضاء متكيف، شاشة لمس على العلبة وصوت LDAC عالي الدقة.",
		tags: ["anker", "soundcore", "earbuds"],
	},
	{
		name: "Huawei FreeBuds Pro 4",
		category: "Audio",
		price: 749,
		stock: 0,
		image: img.earbudsCases,
		description: "سماعات أذن بصوت Hi-Res وعزل ضوضاء ذكي، ميكروفونات واضحة للمكالمات وشحن لاسلكي.",
		tags: ["huawei", "earbuds"],
	},

	// Tablets
	{
		name: "iPad Pro 11 M5 256GB Wi-Fi",
		category: "Tablets",
		price: 4199,
		stock: 9,
		featured: true,
		image: img.ipadPro,
		description: "شاشة Ultra Retina XDR بتقنية OLED الترادفية، شريحة M5 وتصميم نحيف بسماكة 5.3 ملم. يدعم Apple Pencil Pro.",
		tags: ["apple", "ipad", "pro"],
	},
	{
		name: "iPad Air 11 M3 128GB Wi-Fi",
		category: "Tablets",
		price: 2499,
		stock: 18,
		image: img.ipadInHand,
		description: "شريحة M3، شاشة Liquid Retina مقاس 11 بوصة، دعم Apple Pencil Pro وMagic Keyboard.",
		tags: ["apple", "ipad"],
	},
	{
		name: "iPad 11 A16 128GB Wi-Fi",
		category: "Tablets",
		price: 1449,
		stock: 37,
		image: img.ipadPair,
		description: "iPad للدراسة والترفيه بشريحة A16، شاشة 11 بوصة وسعة تخزين 128 جيجابايت.",
		tags: ["apple", "ipad"],
	},
	{
		name: "iPad mini A17 Pro 128GB",
		category: "Tablets",
		price: 2099,
		stock: 10,
		image: img.ipadInHand,
		description: "قوة كبيرة بحجم صغير: شاشة 8.3 بوصة، شريحة A17 Pro ودعم Apple Intelligence.",
		tags: ["apple", "ipad", "mini"],
	},
	{
		name: "Samsung Galaxy Tab S10 Ultra 256GB",
		category: "Tablets",
		price: 4599,
		stock: 4,
		image: img.ipadPro,
		description: "شاشة Dynamic AMOLED 2X ضخمة 14.6 بوصة، قلم S Pen في العلبة ومقاومة للماء IP68.",
		tags: ["samsung", "galaxy tab", "android"],
	},
	{
		name: "Huawei MatePad Pro 13.2",
		category: "Tablets",
		price: 3999,
		stock: 7,
		image: img.ipadPair,
		description: "شاشة OLED مرنة 13.2 بوصة بمعدل 144 هرتز، شاشة PaperMatte لتقليل الانعكاس ودعم قلم M-Pencil.",
		tags: ["huawei", "matepad"],
	},
	{
		name: "Xiaomi Pad 7 256GB",
		category: "Tablets",
		price: 1399,
		stock: 22,
		image: img.ipadInHand,
		description: "شاشة 11.2 بوصة بدقة 3.2K ومعدل 144 هرتز، معالج Snapdragon 7+ Gen 3 وبطارية 8850 مللي أمبير.",
		tags: ["xiaomi", "android"],
	},

	// Monitors
	{
		name: "Samsung Odyssey OLED G6 27 360Hz",
		category: "Monitors",
		price: 2999,
		stock: 7,
		image: img.monitorGaming,
		description: "شاشة ألعاب QD-OLED بدقة QHD ومعدل تحديث 360 هرتز وزمن استجابة 0.03 ملي ثانية.",
		tags: ["samsung", "odyssey", "gaming", "oled"],
	},
	{
		name: "LG UltraGear 27GS95QE OLED 240Hz",
		category: "Monitors",
		price: 2699,
		stock: 6,
		image: img.monitorNeon,
		description: "شاشة OLED مقاس 27 بوصة بدقة QHD ومعدل 240 هرتز، شهادة VESA DisplayHDR True Black 400.",
		tags: ["lg", "ultragear", "gaming", "oled"],
	},
	{
		name: "Dell UltraSharp U2724D 27 QHD",
		category: "Monitors",
		price: 1599,
		stock: 14,
		image: img.monitorDesk,
		description: "شاشة احترافية IPS Black بدقة QHD ومعدل 120 هرتز، ألوان دقيقة ومنافذ USB-C.",
		tags: ["dell", "ultrasharp", "office"],
	},
	{
		name: "ASUS TUF Gaming VG27AQ3A 180Hz",
		category: "Monitors",
		price: 849,
		stock: 26,
		image: img.monitorSetup,
		description: "شاشة ألعاب Fast IPS مقاس 27 بوصة بدقة QHD ومعدل 180 هرتز مع دعم G-SYNC.",
		tags: ["asus", "tuf", "gaming"],
	},
	{
		name: "Samsung Smart Monitor M8 32 4K",
		category: "Monitors",
		price: 2199,
		stock: 8,
		image: img.monitorWhite,
		description: "شاشة ذكية 4K مقاس 32 بوصة مع تطبيقات بث مدمجة وكاميرا SlimFit وتصميم نحيف.",
		tags: ["samsung", "smart monitor", "4k"],
	},
	{
		name: "Apple Studio Display",
		category: "Monitors",
		price: 6499,
		stock: 2,
		image: img.imac,
		description: "شاشة Retina 5K مقاس 27 بوصة، كاميرا 12 ميجابكسل مع Center Stage وست سماعات بصوت مكاني.",
		tags: ["apple", "5k"],
	},

	// Wearables
	{
		name: "Apple Watch Series 11 GPS 46mm",
		category: "Wearables",
		price: 1699,
		stock: 23,
		featured: true,
		image: img.appleWatch,
		images: [img.appleWatchApps],
		description: "شاشة أكبر وأكثر سطوعًا، تنبيهات ارتفاع ضغط الدم، تتبع النوم وبطارية حتى 24 ساعة.",
		tags: ["apple", "watch"],
	},
	{
		name: "Apple Watch Ultra 3",
		category: "Wearables",
		price: 3399,
		stock: 6,
		image: img.appleWatchBlack,
		description: "هيكل من التيتانيوم مقاس 49 ملم، اتصال عبر الأقمار الصناعية للطوارئ، GPS مزدوج التردد وبطارية 42 ساعة.",
		tags: ["apple", "watch", "ultra"],
	},
	{
		name: "Apple Watch SE 3 GPS 44mm",
		category: "Wearables",
		price: 1099,
		stock: 31,
		image: img.appleWatchBlue,
		description: "شاشة دائمة التشغيل، تتبع اللياقة والنوم، كشف السقوط والحوادث بسعر مناسب.",
		tags: ["apple", "watch"],
	},
	{
		name: "Samsung Galaxy Watch8 44mm",
		category: "Wearables",
		price: 1299,
		stock: 15,
		image: img.galaxyWatch,
		description: "ساعة ذكية بتصميم دائري، مؤشر مضادات الأكسدة، مدرب صحي بالذكاء الاصطناعي وتطبيقات Wear OS.",
		tags: ["samsung", "galaxy watch", "wear os"],
	},
	{
		name: "Huawei Watch GT 5 Pro 46mm",
		category: "Wearables",
		price: 1149,
		stock: 12,
		image: img.watchMinimal,
		description: "هيكل من التيتانيوم وزجاج الياقوت، بطارية تصل إلى 14 يومًا وتتبع دقيق للجري والجولف.",
		tags: ["huawei", "watch"],
	},
	{
		name: "Apple Watch Series 11 GPS + Cellular 42mm",
		category: "Wearables",
		price: 2099,
		stock: 3,
		image: img.appleWatchSport,
		description: "اتصال خلوي للمكالمات والرسائل دون الهاتف، هيكل ألومنيوم 42 ملم ومستشعرات صحية متقدمة.",
		tags: ["apple", "watch", "cellular"],
	},
	{
		name: "Xiaomi Smart Band 10",
		category: "Wearables",
		price: 199,
		stock: 70,
		image: img.galaxyWatch,
		description: "سوار رياضي بشاشة AMOLED 1.72 بوصة، أكثر من 150 وضعًا رياضيًا وبطارية حتى 21 يومًا.",
		tags: ["xiaomi", "band", "fitness"],
	},

	// Accessories
	{
		name: "Apple Magic Keyboard Arabic",
		category: "Accessories",
		price: 499,
		stock: 18,
		image: img.keyboard,
		description: "لوحة مفاتيح لاسلكية بتخطيط عربي/إنجليزي، بطارية قابلة للشحن عبر USB-C وتعمل مع Mac وiPad.",
		tags: ["apple", "keyboard"],
	},
	{
		name: "Xiaomi Power Bank 20000mAh 22.5W",
		category: "Accessories",
		price: 129,
		stock: 85,
		image: img.powerBank,
		description: "باور بانك بسعة 20000 مللي أمبير، شحن سريع 22.5 واط ومنفذين USB-A وUSB-C.",
		tags: ["xiaomi", "power bank"],
	},
	{
		name: "Apple 70W USB-C Power Adapter",
		category: "Accessories",
		price: 249,
		stock: 29,
		image: img.charger,
		description: "شاحن أصلي من Apple بقدرة 70 واط لأجهزة MacBook وiPad Pro ويدعم الشحن السريع لهواتف iPhone.",
		tags: ["apple", "charger"],
	},
	{
		name: "Logitech MX Master 3S",
		category: "Accessories",
		price: 449,
		stock: 2,
		image: img.mouse,
		description: "فأرة لاسلكية احترافية بنقرات صامتة، مستشعر 8000 DPI وتمرير سريع MagSpeed للعمل على عدة أجهزة.",
		tags: ["logitech", "mouse"],
	},
	{
		name: "HP Color Laser MFP 179fnw",
		category: "Accessories",
		price: 1099,
		stock: 8,
		image: img.printer,
		description: "طابعة ليزر ملونة متعددة الوظائف: طباعة ونسخ ومسح وفاكس، اتصال Wi-Fi وطباعة من الهاتف.",
		tags: ["hp", "printer"],
	},

	// Eyewear
	{
		name: "Ray-Ban Round Metal RB3447",
		category: "Eyewear",
		price: 649,
		stock: 14,
		image: img.sunglassesRound,
		description: "نظارة شمسية دائرية بإطار معدني ذهبي وعدسات خضراء كلاسيكية بحماية 100% من الأشعة فوق البنفسجية.",
		tags: ["ray-ban", "sunglasses"],
	},
	{
		name: "Ray-Ban Erika RB4171",
		category: "Eyewear",
		price: 599,
		stock: 20,
		image: img.sunglassesSand,
		description: "إطار خفيف من النايلون بعدسات متدرجة، تصميم عصري يناسب الرجال والنساء.",
		tags: ["ray-ban", "sunglasses"],
	},
	{
		name: "Oakley Holbrook OO9102",
		category: "Eyewear",
		price: 699,
		stock: 9,
		image: img.sunglassesBeach,
		description: "نظارة رياضية بعدسات Prizm لتعزيز التباين وإطار O Matter المتين والخفيف.",
		tags: ["oakley", "sunglasses", "sport"],
	},
	{
		name: "Ray-Ban Meta Wayfarer Gen 2",
		category: "Eyewear",
		price: 1499,
		stock: 0,
		image: img.sunglassesSand,
		description: "نظارة ذكية بكاميرا 12 ميجابكسل، تسجيل فيديو 3K، سماعات مفتوحة وبطارية حتى 8 ساعات.",
		tags: ["ray-ban", "meta", "smart glasses"],
	},
	{
		name: "Ray-Ban Wayfarer RB2140",
		category: "Eyewear",
		price: 699,
		stock: 11,
		image: img.sunglassesBeach,
		description: "التصميم الأيقوني منذ 1952 بإطار أسيتات أسود وعدسات G-15 الخضراء.",
		tags: ["ray-ban", "sunglasses", "classic"],
	},
];
